"""empty message

Revision ID: 1979f702187e
Revises: 5655eb2562f8
Create Date: 2019-12-10 19:58:00.734836

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1979f702187e'
down_revision = '5655eb2562f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cart')
    op.add_column('cart', sa.Column('product_id', sa.Integer(), nullable=True))
    op.add_column('cart', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'cart', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'cart', 'product', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('cart', 'product')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('product', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_constraint(None, 'cart', type_='foreignkey')
    op.drop_column('cart', 'user_id')
    op.drop_column('cart', 'product_id')
    op.create_table('user_cart',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('cart_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['cart_id'], ['cart.id'], name='user_cart_cart_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_cart_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='user_cart_pkey')
    )
    # ### end Alembic commands ###
