"""empty message

Revision ID: 5655eb2562f8
Revises: 40fa7062c750
Create Date: 2019-12-10 19:43:20.385875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5655eb2562f8'
down_revision = '40fa7062c750'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
