"""remove test column from User

Revision ID: 76119bab23d8
Revises: 862ca662ff5f
Create Date: 2020-03-20 10:02:42.801845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76119bab23d8'
down_revision = '862ca662ff5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
