"""added test column in User

Revision ID: 862ca662ff5f
Revises: c7d5583c6398
Create Date: 2020-03-20 09:58:01.082924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862ca662ff5f'
down_revision = 'c7d5583c6398'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('test', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'test')
    # ### end Alembic commands ###
