"""empty message

Revision ID: 94c76bbe1ff3
Revises: e82795aa677d
Create Date: 2019-08-12 22:26:39.438985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '94c76bbe1ff3'
down_revision = 'e82795aa677d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('password_hash', sa.String(length=80), nullable=False))
    op.add_column('user', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_unique_constraint(None, 'user', ['lastname'])
    op.create_unique_constraint(None, 'user', ['firstname'])
    op.drop_column('user', 'id')
    op.drop_column('user', 'password')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_column('user', 'user_id')
    op.drop_column('user', 'password_hash')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    # ### end Alembic commands ###
