"""Added new table UserOauth

Revision ID: 98770fb2ee92
Revises: 76119bab23d8
Create Date: 2020-03-23 11:49:30.394014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98770fb2ee92'
down_revision = '76119bab23d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_oauth',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('first_name', sa.String(length=128), nullable=False),
    sa.Column('last_name', sa.String(length=128), nullable=False),
    sa.Column('email', sa.String(length=128), nullable=False),
    sa.Column('picture', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_oauth')
    # ### end Alembic commands ###
