"""empty message

Revision ID: aaefac4fa136
Revises: 1c55214e98a5
Create Date: 2019-09-26 23:01:21.111404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaefac4fa136'
down_revision = '1c55214e98a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('time_date', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'time_date')
    # ### end Alembic commands ###
