"""empty message

Revision ID: c3c0c5b0c47c
Revises: 1979f702187e
Create Date: 2019-12-24 16:17:13.710061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3c0c5b0c47c'
down_revision = '1979f702187e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cart', sa.Column('quantity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cart', 'quantity')
    # ### end Alembic commands ###
