"""Fisrt migrate

Revision ID: c7d5583c6398
Revises: ea9593fe1fe3
Create Date: 2020-03-20 09:54:55.565271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c7d5583c6398'
down_revision = 'ea9593fe1fe3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role2',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='role2_pkey'),
    sa.UniqueConstraint('name', name='role2_name_key')
    )
    # ### end Alembic commands ###
