"""empty message

Revision ID: df3cede710f8
Revises: d74aac5f6760
Create Date: 2019-08-14 00:12:23.591429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3cede710f8'
down_revision = 'd74aac5f6760'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'info')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('info', sa.VARCHAR(length=160), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
